#!/bin/bash
set -euo pipefail

DOTFILES="$(cd "$(dirname "$0")" && pwd)"

info() { printf '\033[34m[info]\033[0m %s\n' "$1"; }
skip() { printf '\033[33m[skip]\033[0m %s\n' "$1"; }
ok()   { printf '\033[32m[ ok ]\033[0m %s\n' "$1"; }

# GNU Stow
if ! command -v stow &>/dev/null; then
    info "Installing GNU Stow..."
    sudo apt-get update -qq && sudo apt-get install -y -qq stow
    ok "Stow installed"
else
    skip "Stow already installed"
fi

# Zellij
if ! command -v zellij &>/dev/null; then
    info "Installing Zellij..."
    case "$(uname -m)" in
        x86_64)  ZELLIJ_ARCH="x86_64-unknown-linux-musl" ;;
        aarch64) ZELLIJ_ARCH="aarch64-unknown-linux-musl" ;;
        *) echo "Unsupported arch: $(uname -m)" >&2; exit 1 ;;
    esac
    mkdir -p "$HOME/.local/bin"
    tmp="$(mktemp -d)"
    curl -fsSL -o "$tmp/zellij.tar.gz" \
        "https://github.com/zellij-org/zellij/releases/latest/download/zellij-${ZELLIJ_ARCH}.tar.gz"
    tar xzf "$tmp/zellij.tar.gz" -C "$tmp"
    mv "$tmp/zellij" "$HOME/.local/bin/zellij"
    rm -rf "$tmp"
    ok "Zellij installed"
else
    skip "Zellij already installed"
fi

# Pup (Datadog CLI) — required by the pup Claude plugin's agents/skills,
# which all shell out to `pup <subcommand>`.
if ! command -v pup &>/dev/null; then
    case "$(uname -m)" in
        x86_64)  PUP_ARCH="x86_64" ;;
        aarch64) PUP_ARCH="aarch64" ;;
        *) PUP_ARCH="" ;;
    esac
    if [ -n "$PUP_ARCH" ]; then
        info "Installing pup..."
        mkdir -p "$HOME/.local/bin"
        tmp="$(mktemp -d)"
        # Release assets are versioned (pup_<ver>_Linux_<arch>.tar.gz), so we
        # resolve the current URL from the GitHub API rather than hardcoding.
        pup_url=$(curl -fsSL https://api.github.com/repos/datadog-labs/pup/releases/latest \
            | grep -oE "https://[^\"]*Linux_${PUP_ARCH}\\.tar\\.gz" | head -1)
        if [ -n "$pup_url" ]; then
            curl -fsSL -o "$tmp/pup.tar.gz" "$pup_url"
            tar xzf "$tmp/pup.tar.gz" -C "$tmp"
            mv "$tmp/pup" "$HOME/.local/bin/pup"
            ok "pup installed"
        else
            skip "pup: couldn't resolve latest Linux_${PUP_ARCH} release asset"
        fi
        rm -rf "$tmp"
    else
        skip "pup: unsupported arch $(uname -m)"
    fi
else
    skip "pup already installed"
fi

# Graphite CLI
if ! command -v gt &>/dev/null; then
    info "Installing Graphite CLI..."
    # NVM installs node outside of PATH for non-interactive shells; source it first.
    if [ -s "$HOME/.nvm/nvm.sh" ]; then
        # shellcheck source=/dev/null
        . "$HOME/.nvm/nvm.sh"
    fi
    if command -v npm &>/dev/null; then
        npm install -g @withgraphite/graphite-cli
        ok "Graphite CLI installed"
    else
        skip "Graphite CLI: npm not available (install Node.js or NVM first)"
    fi
else
    skip "Graphite CLI already installed"
fi

# Graphite repo init
if command -v gt &>/dev/null && git rev-parse --git-dir &>/dev/null 2>&1; then
    info "Initializing Graphite (trunk: main)..."
    gt repo init --trunk main && ok "Graphite initialized" || skip "Graphite already initialized"
fi

# Oh My Zsh
if [ ! -d "$HOME/.oh-my-zsh" ]; then
    info "Installing Oh My Zsh..."
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
    ok "Oh My Zsh installed"
else
    skip "Oh My Zsh already installed"
fi

# zsh-autosuggestions
if [ ! -d "$HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions" ]; then
    info "Installing zsh-autosuggestions..."
    git clone https://github.com/zsh-users/zsh-autosuggestions "$HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    ok "zsh-autosuggestions installed"
else
    skip "zsh-autosuggestions already installed"
fi

# zsh-syntax-highlighting
if [ ! -d "$HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting" ]; then
    info "Installing zsh-syntax-highlighting..."
    git clone https://github.com/zsh-users/zsh-syntax-highlighting "$HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
    ok "zsh-syntax-highlighting installed"
else
    skip "zsh-syntax-highlighting already installed"
fi

PACKAGES="claude gh git zsh zellij"

# Back up existing files that would conflict with stow symlinks
# (e.g. .zshrc from the devcontainer base image, or ~/.config/zellij/config.kdl
# auto-generated by zellij on first run). Recursively finds every file each
# package would install and backs up any real file (not symlink) at the target.
#
# The `-ef` check skips files already stowed via a parent directory symlink:
# stow sometimes folds a whole subdir into one symlink (e.g.
# ~/.claude/statusline -> dotfiles/.../statusline), which leaves the files
# inside reachable as real files but already equal to src. Without this check,
# the mv below would rename files *inside the dotfiles repo itself*.
for pkg in $PACKAGES; do
    while IFS= read -r -d '' src; do
        target="$HOME/${src#$DOTFILES/$pkg/}"
        if [ -f "$target" ] && [ ! -L "$target" ] && ! [ "$target" -ef "$src" ]; then
            info "Backing up $target to $target.bak"
            mv "$target" "$target.bak"
        fi
    done < <(find "$DOTFILES/$pkg" -mindepth 1 -type f -print0)
done

info "Stowing dotfiles ($PACKAGES)..."
cd "$DOTFILES"
stow -t ~ $PACKAGES
ok "All packages stowed"

# Set zsh as default shell
if [ "$(getent passwd "$(id -un)" | cut -d: -f7)" != "/usr/bin/zsh" ]; then
    info "Setting default shell to zsh..."
    sudo chsh "$(id -un)" --shell "/usr/bin/zsh"
    ok "Default shell set to zsh"
else
    skip "Default shell already zsh"
fi

# EFS network directory — persist credentials across Ona instances.
# Set EFS_MOUNT_POINT in Ona secrets to enable (e.g. /efs).
EFS_DIR="${EFS_MOUNT_POINT:-}"
if [ -n "$EFS_DIR" ]; then
    # EFS may not be mounted yet (dotfiles can run before post-start.sh).
    # Create symlinks anyway — they'll resolve once the mount completes.
    info "EFS_MOUNT_POINT=$EFS_DIR — linking credentials (mount may still be in progress)..."

    # Links a file or directory from $HOME to $EFS_DIR. On the first machine
    # where a file exists locally but not yet on EFS, migrates it over.
    # On subsequent machines, just creates the symlink.
    link_to_efs() {
        local name="$1"
        local src="$HOME/$name"
        local dst="$EFS_DIR/$name"

        # Already correct
        if [ -L "$src" ] && [ "$(readlink "$src")" = "$dst" ]; then
            return
        fi

        # Migrate existing file/dir to EFS if destination doesn't exist yet
        if [ -d "$EFS_DIR" ] && [ ! -e "$dst" ] && [ -e "$src" ] && [ ! -L "$src" ]; then
            mkdir -p "$(dirname "$dst")"
            mv "$src" "$dst"
        fi

        # Remove stale real file/dir or wrong symlink at src
        if [ -e "$src" ] || [ -L "$src" ]; then
            rm -rf "$src"
        fi

        mkdir -p "$(dirname "$src")"
        ln -s "$dst" "$src"
    }

    link_to_efs ".claude.json"              # Claude Code OAuth + API key
    link_to_efs ".claude/.credentials.json"  # Claude Code credentials
    link_to_efs ".config/gh/hosts.yml"       # GitHub CLI auth
    link_to_efs ".config/acli"               # Atlassian CLI non-secret config (site, email)
    link_to_efs ".aws"                       # AWS config
    link_to_efs ".zsh_history"               # Shell history

    ok "EFS credential symlinks configured"
else
    skip "EFS_MOUNT_POINT not set (set it in Ona secrets to enable)"
fi

# Atlassian CLI auth — auto-authenticate using an API token.
#
# ACLI stores the OAuth/API token in the OS keyring (libsecret/DBus), which is
# per-machine and ephemeral — EFS can only persist the YAML config (site,
# email), not the token itself. So every fresh Ona instance boots logged out.
#
# Fix: set JIRA_API_TOKEN in Ona secrets (same pattern as EFS_MOUNT_POINT).
# Create a token at https://id.atlassian.com/manage-profile/security/api-tokens.
# API tokens are long-lived, so one token re-auths every new instance non-
# interactively.
JIRA_SITE="${JIRA_SITE:-vanta.atlassian.net}"
if [ -n "${JIRA_API_TOKEN:-}" ]; then
    # Install ACLI if missing
    if ! command -v acli &>/dev/null; then
        case "$(uname -m)" in
            x86_64)  ACLI_URL="https://acli.atlassian.com/linux/latest/acli_linux_amd64/acli" ;;
            aarch64) ACLI_URL="https://acli.atlassian.com/linux/latest/acli_linux_arm64/acli" ;;
            *) ACLI_URL="" ;;
        esac
        if [ -n "$ACLI_URL" ]; then
            info "Installing ACLI to ~/.local/bin..."
            mkdir -p "$HOME/.local/bin"
            curl -fsSL -o "$HOME/.local/bin/acli" "$ACLI_URL"
            chmod +x "$HOME/.local/bin/acli"
            export PATH="$HOME/.local/bin:$PATH"
            ok "ACLI installed"
        else
            skip "ACLI install: unsupported arch $(uname -m)"
        fi
    fi

    if command -v acli &>/dev/null; then
        if acli jira auth status &>/dev/null; then
            skip "ACLI already authenticated"
        else
            JIRA_EMAIL="${JIRA_EMAIL:-$(git config --global --get user.email 2>/dev/null || true)}"
            if [ -z "$JIRA_EMAIL" ]; then
                skip "ACLI auth: no email (set JIRA_EMAIL, or git config --global user.email)"
            else
                info "Authenticating ACLI as $JIRA_EMAIL @ $JIRA_SITE..."
                # File redirect, not a pipe — acli reads the token via TTY
                # handling that breaks with stdin pipes.
                token_file="$(mktemp)"
                chmod 600 "$token_file"
                printf '%s' "$JIRA_API_TOKEN" > "$token_file"
                if acli jira auth login \
                        --site "$JIRA_SITE" \
                        --email "$JIRA_EMAIL" \
                        --token < "$token_file" &>/dev/null; then
                    ok "ACLI authenticated"
                else
                    info "ACLI auth failed — check JIRA_API_TOKEN is valid and email matches"
                fi
                rm -f "$token_file"
            fi
        fi
    fi
else
    skip "JIRA_API_TOKEN not set (set it in Ona secrets for auto-ACLI-auth)"
fi
